// For top right menu button
const SHOW_MENU_CONTENT = "SHOW_MENU_CONTENT";
const HIDE_MENU_CONTENT = "HIDE_MENU_CONTENT";

// For top left navbar button
const SHOW_HIDE_NAV_BAR = "CONTROL_NAV_BAR";

// For navbar items
const SHOW_HIDE_NAV_BAR_SUB_ITEM = "CONTROL_NAV_BAR_ITEM";

// For tabs
const SWITCHING_TABS = "SWITCHING_TABS";
const RESET_TABS = "RESET_TABS";

// Switch bar form
const SWITCHING_BARS = "SWITCHING_BARS";

export default {
  SHOW_MENU_CONTENT,
  HIDE_MENU_CONTENT,
  SHOW_HIDE_NAV_BAR,
  SHOW_HIDE_NAV_BAR_SUB_ITEM,
  SWITCHING_TABS,
  RESET_TABS,
  SWITCHING_BARS,
}