// For top right menu button
const SHOW_MENU_CONTENT = "SHOW_MENU_CONTENT";
const HIDE_MENU_CONTENT = "HIDE_MENU_CONTENT";

// For top left navbar button
const SHOW_HIDE_NAV_BAR = "CONTROL_NAV_BAR";

// For navbar items
const SHOW_HIDE_NAV_BAR_SUB_ITEM = "CONTROL_NAV_BAR_ITEM";

// For tabs
const SWITCHING_TABS = "SWITCHING_TABS";
const RESET_TABS = "RESET_TABS";

// For bar chart
const SWITCHING_BARS = "SWITCHING_BARS";

// For dialog
const OPEN_CLOSE_DIALOG = "OPEN_CLOSE_DIALOG";

// For Nested List
const OPEN_CLOSE_NESTED_LIST = "OPEN_CLOSE_NESTED_LIST";

// For Notification
const OPEN_CLOSE_NOTIFICATION = "OPEN_CLOSE_NOTIFICATION";

// For Table
const CHANGE_TABLE_PAGE = "CHANGE_TABLE_PAGE";
const CHANGE_ROWS_PER_PAGE = "CHANGE_ROWS_PER_PAGE";
const CHANGE_COLUMN_ORDER = "CHANGE_COLUMN_ORDER";
const CHANGE_COLUMN_ORDER_BY = "CHANGE_COLUMN_ORDER_BY";

// For Iconography
const OPEN_CODE_DIALOG = "OPEN_CODE_DIALOG";
const CLOSE_CODE_DIALOG = "CLOSE_CODE_DIALOG";

export default {
  SHOW_MENU_CONTENT,
  HIDE_MENU_CONTENT,
  SHOW_HIDE_NAV_BAR,
  SHOW_HIDE_NAV_BAR_SUB_ITEM,
  SWITCHING_TABS,
  RESET_TABS,
  SWITCHING_BARS,
  OPEN_CLOSE_DIALOG,
  OPEN_CLOSE_NESTED_LIST,
  OPEN_CLOSE_NOTIFICATION,
  CHANGE_TABLE_PAGE,
  CHANGE_ROWS_PER_PAGE,
  CHANGE_COLUMN_ORDER,
  CHANGE_COLUMN_ORDER_BY,
  OPEN_CODE_DIALOG,
  CLOSE_CODE_DIALOG
};
